version: '3'

services:

  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: deckhub
      POSTGRES_PASSWORD: SecretSquirrel
    ports:
      - 5432:5432
  
  redis:
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
