apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: questions
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: questions
    spec:
      containers:
      - image: deckhub/questions:1.0.0-alpha2
        imagePullPolicy: Always
        name: questions
        env:
          - name: Runtime__PathBase
            value: '/questions'
          - name: Redis__Host
            value: 'redis'
          - name: AppMetrics__InfluxDbServer
            value: 'http://rlmetrics.eastus.cloudapp.azure.com:8086'
          - name: AppMetrics__InfluxDbDatabase
            value: 'deckhub'
          - name: ConnectionStrings__Questions
            valueFrom:
              secretKeyRef:
                name: questions-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: questions
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: questions
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: questions
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /questions
        backend:
          serviceName: questions
          servicePort: 80
