apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: questions
  namespace: shtik
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: questions
    spec:
      containers:
      - image: shtik/questions:1.1.0
        imagePullPolicy: Always
        name: questions
        env:
          - name: ConnectionStrings__Questions
            valueFrom:
              secretKeyRef:
                name: questions-db
                key: connstr
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: questions
  namespace: shtik
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: questions