apiVersion: batch/v1
kind: Job
metadata:
  name: questions-migrate
  namespace: deckhub
spec:
  template:
    metadata:
      name: questions-migrate
    spec:
      containers:
      - name: questions-migrate
        image: deckhub/questions-migrate:1.0.0-alpha2
        args: ["$(SECRET_CONNSTR)"]
        env:
          - name: SECRET_CONNSTR
            valueFrom:
              secretKeyRef:
                name: questions-db
                key: connstr
      restartPolicy: OnFailure