// <auto-generated />
using System;
using DeckHub.Questions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeckHub.Questions.Migrate.Migrations
{
    [DbContext(typeof(QuestionContext))]
    partial class QuestionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DeckHub.Questions.Data.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("QuestionId");

                    b.Property<string>("QuestionUuid")
                        .HasMaxLength(40);

                    b.Property<string>("Text");

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("User")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionUuid");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("DeckHub.Questions.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From")
                        .HasMaxLength(16);

                    b.Property<string>("Show")
                        .HasMaxLength(256);

                    b.Property<int>("Slide");

                    b.Property<string>("Text");

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("Uuid")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("Show");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DeckHub.Questions.Data.Answer", b =>
                {
                    b.HasOne("DeckHub.Questions.Data.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
